/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ltd_lifesearchapp_Detect_RadarData */

#ifndef _Included_com_ltd_lifesearchapp_Detect_RadarData
#define _Included_com_ltd_lifesearchapp_Detect_RadarData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ltd_lifesearchapp_Detect_RadarData
 * Method:    memCopy
 * Signature: ([SI[BII)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_RadarData_memCopy
  (JNIEnv *, jclass, jshortArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
