/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ltdpro_BaseDetect */

#ifndef _Included_com_ltdpro_BaseDetect
#define _Included_com_ltdpro_BaseDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    detect_body
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_detect_1body
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    init_body
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_init_1body
  (JNIEnv *, jclass);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    init_breath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_init_1breath
  (JNIEnv *, jclass);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    changeParams
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_changeParams
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    detect_body_pre
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_detect_1body_1pre
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    detect_breath_pre
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_detect_1breath_1pre
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    detect_breath
 * Signature: ([SF)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_detect_1breath
  (JNIEnv *, jclass, jshortArray, jfloat);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    setMultiMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ltdpro_BaseDetect_setMultiMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ltdpro_BaseDetect
 * Method:    getMultiMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ltdpro_BaseDetect_getMultiMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
