/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ltd_lifesearchapp_RadarData */

#ifndef _Included_com_ltd_lifesearchapp_RadarData
#define _Included_com_ltd_lifesearchapp_RadarData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ltd_lifesearchapp_RadarData
 * Method:    _memory_copy
 * Signature: ([BI[SII)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_RadarData__1memory_1copy
  (JNIEnv *, jclass, jbyteArray, jint, jshortArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
