/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ltd_lifesearchapp_Detect_DetectUtil */

#ifndef _Included_com_ltd_lifesearchapp_Detect_DetectUtil
#define _Included_com_ltd_lifesearchapp_Detect_DetectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    detect_body
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_detect_1body
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    init_body
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_init_1body
  (JNIEnv *, jclass);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    init_breath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_init_1breath
  (JNIEnv *, jclass);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    changeParams
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_changeParams
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    detect_body_pre
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_detect_1body_1pre
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    detect_breath_pre
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_detect_1breath_1pre
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    detect_breath
 * Signature: ([SF)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_detect_1breath
  (JNIEnv *, jclass, jshortArray, jfloat);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    setMultiMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_setMultiMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ltd_lifesearchapp_Detect_DetectUtil
 * Method:    getMultiMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ltd_lifesearchapp_Detect_DetectUtil_getMultiMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
